### ISSUE TITLE
Analyze Usability #2: Include BOM Timestamp and Serial Number

### ISSUE THREAD

**Issue by msymons** [CycloneDX/cyclonedx-cli#134]
Analyze output includes BOM name and version, resolving #78.  Example:

```
Analysis results for some-project@1.0.26-SNAPSHOT:

Components with multiple versions:

commons-codec:commons-codec versions: 1.15 1.3
commons-io:commons-io versions: 2.8.0 2.4
```

It would be useful for the output to also include BOM  `timestamp` and `serialNumber`.

Use Case:  inclusion of output into a Slack DM, email, or GitHub PR review comment where the timestamp for the BOM generation can be very different from (say) the PR comment timestamp but very relevant to commit timestamps.

**Comment by coderpatros** [comment]
I also added BOM version to the output.

Available in v0.16.0
