### ISSUE TITLE
Add merge arguments to set metadata values on the merged BOM

### ISSUE THREAD

**Issue by khuey** [CycloneDX/cyclonedx-cli#153]
I'd like to be able to do things like set the authors and supplier in the BOM's metadata when merging.

**Comment by coderpatros** [comment]
This is likely to be implemented as a specific command in #108 with this use case in mind.

Likely to end up with usage something like this...

`cyclonedx merge --input-files bom1.xml bom2.xml | cyclonedx metadata --set author.name="Some Person" --set supplier.name="Some Company" --output-file bom.xml`

That way in can be implemented once and made use of for multiple use cases.

**Comment by khuey** [comment]
Sounds great.

**Comment by stevespringett** [comment]
@coderpatros Any updates on this? I've run into this issue when merging the DT bom generated from Maven and the pre-build bom containing all the services DT relies on. I'm wanting to merge the boms but I'm loosing metadata information.

**Comment by waarg** [comment]
Hi @coderpatros 

Do you plan on implementing this any time soon? We could really do with it in our CD - at the moment we have an extra step to insert the metadata, after the merge, but if cyclonedx-cli could do it, it would be much better.

**Comment by nscuro** [comment]
@coderpatros I think this one can be closed as #240 has been merged?
