### ISSUE TITLE
Enable appending of XML and JSON SBOMs

### ISSUE THREAD

**Issue by TraceyOnim** [CycloneDX/cyclonedx-cli#18]
Cyclonedx-cli should support appending of both XML and JSON outputs. Currently, only XML outputs can be appended. 
 Here is a link related to the issue reported  https://github.com/CycloneDX/cyclonedx-node-module/issues/90

**Comment by coderpatros** [comment]
Hi @TraceyOnim this is definitely planned soon.

**Comment by coderpatros** [comment]
In the meantime, you can use the node implementation to merge XML SBOMs and use this tool to convert the output to JSON.

**Comment by TraceyOnim** [comment]
That's great. 
 I have  used it to merge XML SBOMs and also generating JSON outputs its working as expected

**Comment by coderpatros** [comment]
@TraceyOnim this is now available in v0.11.0, at the moment it only combines components. It ignores additional BOM level elements like metadata and services.
