### ISSUE TITLE
Merge command corrupts resulting SBOM

### ISSUE THREAD

**Issue by kkovaletp** [CycloneDX/cyclonedx-cli#219]
I've merged 2 SBOMs, but found that resulting SBOM doesn't contain metadata.component from original SBOMs.
Executed command:
`cyclonedx-cli merge --input-files ${NGINX_REPORTS}/Details/Anchore-SBOM.xml ${NGINX_REPORTS}/Details/CI-SBOM.xml --output-file ${NGINX_REPORTS}/Details/SBOM-merged.xml`

Here is what I see at the end of the `SBOM-merged.xml`:
```
    <component type="library" bom-ref="ac6e20ae-da71-40c0-aa23-697d76d5fad3">
      <author>William Turner</author>
      <name>pyxlsb</name>
      <version>1.0.8</version>
      <licenses>
        <expression>LGPLv3+</expression>
      </licenses>
      <purl>pkg:pypi/pyxlsb@1.0.8</purl>
    </component>
  </components>
</bom> <expression>LGPLv3+</expression>
      </licenses>
      <purl>pkg:pypi/pyxlsb@1.0.8</purl>
    </component>
  </components>
</bom>
```

**Comment by coderpatros** [comment]
Is this a duplicate of #218?

**Comment by kkovaletp** [comment]
No, it is not. #218 is about `metadata` section and this one is about end of the resulting file
