### ISSUE TITLE
Cannot use Merge using Docker Image Terminal of Kali Linux

### ISSUE THREAD

**Issue by almitte** [CycloneDX/cyclonedx-cli#229]
Hello,

I wanted to merge my excisting SBoMs of serveral microservices in on combined Project-SBoM. 
When performing the following command: 
`docker run cyclonedx/cyclonedx-cli merge --input-files /home/kalimitteuser/downloads/2.json /home/kalimitteuser/downloads/1.json --version 1.139.16 --output-file /home/kalimitteuser/downloads/sbom_all.json` 
I get this error: 
![grafik](https://user-images.githubusercontent.com/101641863/161083620-b06fc205-7b63-4589-ba9c-5a142e1a42ef.png)

Paths are correct and even if I cd into the Downloads folder and perform it without the path it gives me the same error.
Docker image is downloaded:
![grafik](https://user-images.githubusercontent.com/101641863/161084832-6f91a3e7-50c7-488c-b22e-43db469db910.png)

Thanks in advance.

**Comment by stevespringett** [comment]
The paths specified reference the Docker container, not the Docker host where the BOMs are located.

Trying changing the command to something like:

```bash
docker run -v /home/kalimitteuser/downloads:/work cyclonedx/cyclonedx-cli merge \
  --input-files /work/2.json /work/1.json --version 1.139.16 \
  --output-file /work/sbom_all.json
```

**Comment by almitte** [comment]
Works like a dream thank you.
