### ISSUE TITLE
Pre-Existing output file is not truncated when overwritten

### ISSUE THREAD

**Issue by flemminglau** [CycloneDX/cyclonedx-cli#255]
In a merge operation in case the output file already exists and is thereby overwritten the previous content is not first truncated.

The result is that in case the new file content is shorter than the old file content the remaining part of the old file is left behind at the end of the new file.

The expectation would be that an existing output file is completely removed when overwritten.

**Comment by Andrew-Russell-fingo** [comment]
Aha, that is why I am seeing this problem with corrupted json files. thanks. easily fixed in my use-case.

**Comment by Serraniel** [comment]
Nice to see there already is a fix in the pipeline. We have run into the same issue :)
