### ISSUE TITLE
Lots of missing metadata required by EO 14028

### ISSUE THREAD

**Issue by sej7278** [CycloneDX/cyclonedx-cli#311]
Not sure if I'm doing something wrong, but the [minimum requirements for SBOM data](https://www.ntia.gov/report/2021/minimum-elements-software-bill-materials-sbom) don't seem to be found in the SBOM generated by this tool e.g.

 * Supplier name
 * License
 * Author of SBOM data
 * Other unique identifiers - no CPE data/purl
 *  Dependency relationship

All I get when scanning a directory of RPM's and patch files (or even C/C++ sourcecode) is:

 * Component name
 * Version of the component - incorrectly set to `0.0.0-sha1sum`
 * Cryptographic hash
 * Timestamp

```xml
<component type="file">
  <name>openssl-3.0.1-hobbled.tar.xz</name>
  <version>0.0.0-1170b5119f0e</version>
  <hashes>
    <hash alg="SHA-1">1170b5119f0e591f6a2515d099abd06d0184f77c</hash>
    <hash alg="SHA-256">77afb2489a18db760592099394568cd2828f654580dcf88259ca0474bcf4ba73</hash>
    <hash alg="SHA-384">9e22d79cb8c48d87c4ba90724ba9105ac6b3b375c5a7bfacc76a483562bb9ff61fecf9bf32f8d05b3e7895ed1a15770b</hash>
    <hash alg="SHA-512">8819d02a6961c2398d0fb4003f25a322f752254b5c3440cd3e9456df5c56dadbc8a1aa6f821f176941293d67771304b3a565b3b8ce7a3ac0b7ad221da97c4dfe</hash>
  </hashes>
</component>
```

There's also no packages section or namespace....?

Is there a way to pass in the metadata perhaps as a cli argument or input file? #108

The Maven plugin seems to have most of this data, so with the cli tool being its "upstream", I assume I'm missing some instructions?

**Comment by stevespringett** [comment]
The CycloneDX CLI is more of a utility. It can produce source SBOMs, which are not useful for distribution. The CLI does not perform any analysis, so it's doesn't have any functionality built-in to try to determine the contents of `openssl-3.0.1-hobbled.tar.xz`. There are other CycloneDX tools that support RPMs and other Linux package systems that will do a much better job than the CLI. Not sure about unmanaged C/C++.  For managed C/C++, there's the Conan plugin which is recommended.

**Comment by sej7278** [comment]
ok thanks, of the tools i've looked at so far, this is probably the most useful for c++/rpm so i was hoping i was just missing something
