### ISSUE TITLE
Shows inccorect licesnse Id for "TTWL"

### ISSUE THREAD

**Issue by boravinod145** [CycloneDX/cyclonedx-cli#357]
SBOM validate command shows an invalid license id for "TTWL", but is listed as a valid license id in CycloneDX specifications [Reff [https://cyclonedx.org/docs/1.5/json/#components_items_licenses_oneOf_i0_items_license_id](https://cyclonedx.org/docs/1.5/json/#components_items_licenses_oneOf_i0_items_license_id)].

**Comment by andreas-hilti** [comment]
I think the schema
https://github.com/CycloneDX/cyclonedx-dotnet-library/blob/main/src/CycloneDX.Core/Schemas/spdx.schema.json
would need to be updated and then, the cyclonedx-dotnet-library version used here would need updated accordingly. Compare
https://github.com/CycloneDX/cyclonedx-dotnet-library/issues/277

**Comment by mtsfoni** [comment]
Schema was updated. If you still have problems feel free to reopen this issue or open a new one.
