### ISSUE TITLE
Add Support for Reporting "Multiple Versions of Same Component"

### ISSUE THREAD

**Issue by msymons** [CycloneDX/cyclonedx-cli#38]
This is an enhancement that is similar to #31, but this time I an interested in examining a single SBOM, rather than comparing two SBOM with each other.

I mainly use Maven and find that clashing component versions are normally resolved correctly, such that it is the latest version that actually gets included in my shaded jar.  But it does not _always_ work...  occasionally, it's the older version that is used.

However,  my SBOMs report all versions... so all that is needed is to simply be able to analyse the SBOM and report that  a clash exists.  Once spotted,  such clashes are easy to resolve.

**Comment by coderpatros** [comment]
Available in v0.8.0
