### ISSUE TITLE
`cyclonedx` does not know about all SPDX license IDs

### ISSUE THREAD

**Issue by tmuehlbacher** [CycloneDX/cyclonedx-cli#384]
The CycloneDX spec v1.6 states that `id` within the `license` object shall be

> A valid SPDX license ID

However, the spec does not actually list all valid SPDX IDs, such as `"hdparm"`. The spec does list `"Xfig"`, but cyclonedx-cli does not recognize *either* of these two when using `cyclonedx validate`.

There may be more SPDX IDs that are not present in either the CLI or the spec, I don't know for sure.

At the same time, sbom-utility does recognize both of these IDs correctly, though technically recognizing `"hdparm"` could be considered breaking the spec.

**Comment by andreas-hilti** [comment]
@tmuehlbacher Can you please try with the latest version of the application? (I'm assuming you used 0.25.0, right?)
https://github.com/CycloneDX/cyclonedx-dotnet-library/blob/main/src/CycloneDX.Core/Schemas/spdx.schema.json
was updated a couple of months ago and it should contain both "Xfig" as well "hdparm".
