### ISSUE TITLE
Analyze: improve text output-format

### ISSUE THREAD

**Issue by msymons** [CycloneDX/cyclonedx-cli#61]
Output from analyze  0.10.0 when specifying text as output-format is hard to read when there are muliple components.  Example:

```
$ ./cyclonedx-win-x86.exe analyze --input-file my-bom.xml --output-format text --multiple-component-versions
Components with multiple versions:

javax.ws.rs-api versions: 2.0.1 2.1.1javax.inject versions: 2.5.0-b32 1elasticsearch versions: 2.4.7 5.6.4thread-context versions: 1.1.11 1.1.13rest-api-client versions: 0.4.8 0.4.11usage-event-service-v1-api versions: 1.1.16 1.1.9
```
Note that the versions for each component run into the name for the next.  I was using Git BASH and not Windows Command Prompt.

Would it be possible to improve formatting?  Perhaps with a comma, or maybe a carriage return...

```
$ ./cyclonedx-win-x86.exe analyze --input-file my-bom.xml --output-format text --multiple-component-versions
Components with multiple versions:

javax.ws.rs-api versions: 2.0.1 2.1.1
javax.inject versions: 2.5.0-b32 1
elasticsearch versions: 2.4.7 5.6.4
thread-context versions: 1.1.11 1.1.13
rest-api-client versions: 0.4.8 0.4.11
usage-event-service-v1-api versions: 1.1.16 1.1.9
```

**Comment by coderpatros** [comment]
Available in release 0.10.1

**Comment by msymons** [comment]
@coderpatros , the fix does not seem to have worked for me.  I got identical output in v0.10.1 as I did with 0.10.0.

I checked the version of Git BASH that I was using.  It was 2.26.0... but upgrading to the latest (2.30.0) did not help.

I also tested using standard Windows Command Prompt.  Same problem.

This is all on Windows 10 Pro (Build 18363).

**Comment by msymons** [comment]
Using v0.10.2, I performed testing and the problem is resolved. 

```
$ ./cyclonedx-win-x86.exe analyze --input-file my-bom.xml--output-format text --multiple-component-versions
Components with multiple versions:

javax.ws.rs-api versions: 2.0.1 2.1.1
thread-context versions: 1.1.11 1.1.13
rest-api-client versions: 0.4.8 0.4.11
usage-event-service-v1-api versions: 1.1.16 1.1.9
```
Correct wrapping...  and the false positives (reported in #62) are gone.
