### ISSUE TITLE
Add support for SPDX cpe22Type and cpe23Type

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/cyclonedx-cli#9]
CycloneDX supports a single CPE field which enforces compliance to the CPE 2.2 or CPE 2.3 spec. This enhancement is to add logic that:
1) Automatically determines CPE spec version in a CycloneDX BOM (when present)
2) Outputs either cpe22Type or cpe23Type based on the above result

**Comment by coderpatros** [comment]
Available in v0.3.0

**Comment by 0x73746F66** [comment]
was there regression? It's not there now. Also I see no issues mentioning SPDX-2.3 so perhaps this is the most appropriate place to ask as CPE and Purl support was part of SPDX-2.3 release
